
[functions.send-whatsapp-confirmation]
enabled = true
verify_jwt = true
import_map = "./functions/send-whatsapp-confirmation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-whatsapp-confirmation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-whatsapp-confirmation/*.html" ]

[functions.notify-restaurateur]
enabled = true
verify_jwt = true
import_map = "./functions/notify-restaurateur/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-restaurateur/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-restaurateur/*.html" ]
